version: '3.8'

services:
  postgres:
    image: postgres:14.13-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_approval_development
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rails:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/expense_approval_development
      RAILS_ENV: development
    depends_on:
      - postgres
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache: