source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

# Core Rails
gem "rails", "~> 7.1.0"
gem "logger", "~> 1.6"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

# API functionality
gem "jbuilder"
gem "bootsnap", ">= 1.4.4", require: false

# Authentication & Authorization
gem "devise"
gem "pundit", "~> 2.3"
gem "jwt"

# State Machine
gem "aasm", "~> 5.5"

# Utilities
gem "bcrypt", "~> 3.1.7"
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
end